# Generated by Django 5.0.6 on 2024-06-15 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('required_score', models.IntegerField()),
                ('last_play_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('guest_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.IntegerField()),
                ('play_score', models.IntegerField(default=0)),
                ('last_play_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserGameScore',
            fields=[
                ('user_game_score_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('play_time', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MSGapp.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MSGapp.user')),
            ],
        ),
    ]
